Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 60

Metrics/AbcSize:
  Max: 20